site_name: Donovan's Actuarial Class - MYGA Foundation
site_url: https://DonovanHou2023.github.io/dac-myga-intro
docs_dir: docs
site_dir: mkdocs_site
nav:
  - Home: index.md
  - Classes:
      - Class 1: class_materials/cm1.md
      - Class 2: class_materials/cm2.md
      - Class 3: class_materials/cm3.md
      - Class 4: class_materials/cm4.md
      - Class 5: class_materials/cm5.md
  - Homework:
      - Homework 1: homeworks/hw1.md
      - Homework 2: homeworks/hw2.md
      - Homework 3: homeworks/hw3.md
      - Homework 4: homeworks/hw4.md
      - Homework 5: homeworks/hw5.md
  - Projects:
      - Project 1: projects/proj_1_illustration.md
      - Project 2: projects/proj_2_carvm_calculation.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    scheme: default
    primary: '#0B3D91'    # deep blue primary
    accent: '#0A75D1'     # slightly brighter accent

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  # MathJax for rendering LaTeX-style math ($...$ and $$...$$)
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
