site_name: Donovan's Actuarial Class - MYGA Foundation
site_url: https://DonovanHou2023.github.io/dac-myga-intro
docs_dir: docs
site_dir: mkdocs_site
nav:
  - Home: index.md
  - Lessons:
      - Lesson 1: lessons/lecture1.md
theme:
  name: material
  palette:
    scheme: default
    primary: '#0B3D91'    # deep blue primary
    accent: '#0A75D1'     # slightly brighter accent

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search

extra_javascript:
  # MathJax for rendering LaTeX-style math ($...$ and $$...$$)
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js
